# Generated by Django 4.2 on 2023-04-23 09:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название Объявления')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Название Объявления')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Название Объявления')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='Название Объявления')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое объявления')),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое объявления')),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое объявления')),
                ('body_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое объявления')),
                ('image', models.ImageField(upload_to='images/ads/')),
            ],
            options={
                'verbose_name': 'Обьявление',
                'verbose_name_plural': 'Обьявления',
            },
        ),
        migrations.CreateModel(
            name='Anons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название Анонса')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Название Анонса')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Название Анонса')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='Название Анонса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/anons/')),
            ],
            options={
                'verbose_name': 'Анонс',
                'verbose_name_plural': 'Анонсы',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('title_en', models.CharField(max_length=123, null=True)),
                ('title_ru', models.CharField(max_length=123, null=True)),
                ('title_ky', models.CharField(max_length=123, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/stat/')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Учебное заведение',
                'verbose_name_plural': 'Учебные заведения',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='SocSeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('exp', models.IntegerField(verbose_name='Опыт работы')),
                ('image', models.ImageField(upload_to='images/teacher/')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.education')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('title_ru', models.CharField(max_length=128, null=True)),
                ('title_ky', models.CharField(max_length=128, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/stat/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_pages', to='app.education')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='EduImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('edu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edu_images', to='app.education')),
            ],
            options={
                'verbose_name': 'Картинки на слайде',
                'verbose_name_plural': 'Картинки на слайде',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название курса')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название курса')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название курса')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('content_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/teacher/')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.education')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направлении',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.page')),
            ],
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('title_en', models.CharField(max_length=128, null=True)),
                ('title_ru', models.CharField(max_length=128, null=True)),
                ('title_ky', models.CharField(max_length=128, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_ky', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stat/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks_cat', to='app.category')),
            ],
            options={
                'verbose_name': 'Страница на странице',
                'verbose_name_plural': 'Страницы на странице',
            },
        ),
    ]
