# Generated by Django 4.2 on 2023-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socseti',
            name='title',
            field=models.URLField(max_length=123),
        ),
    ]
